In [ ]:
Name  : arivazhagan.B

Topic : data Preprocessing Using Pandas

Email : barivazhagan8@gmail.com

## Zomato Order delivery dataset

I will be  working with a **Zomato Order Delivery Dataset** for these excercise.For now ,I will focus on the **Pandas** using analyzing,manipulation and cleaning of the data.

**import numpy and pandas**

In [ ]:
import pandas as pd
import numpy as np

**Read in csv file us dataframe called df**

In [15]:

df=pd.read_csv(r'C:\Users\ELCOT\Desktop\csv file\order_history_kaggle_data.csv')
df

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,"03:26 AM, January 30 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),...,NaN,NaN,NaN,NaN,NaN,14.32,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,"02:44 AM, January 29 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,...,NaN,NaN,NaN,NaN,NaN,NaN,10.8,Missed,NaN,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,"10:05 PM, January 24 2025",Delivered,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,...,5.0,Yummy food! Delicious food! Lip smacking food!...,NaN,NaN,NaN,16.27,9.4,Incorrectly,NaN,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,"02:27 PM, January 21 2025",Delivered,Zomato Delivery,9km,1 x Ooh Saucy Fries,...,4.0,The peri peri fries were truly so tasty and de...,NaN,NaN,NaN,12.77,1.3,Correctly,NaN,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,"02:55 AM, January 21 2025",Delivered,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,...,NaN,NaN,NaN,NaN,NaN,16.52,8.7,Correctly,NaN,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

info()-It allow us to show  number of rows and columns ,dtype and storage in your dataset

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21321 entries, 0 to 21320
Data columns (total 29 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Restaurant ID                                       21321 non-null  int64
 1   Restaurant name                                     21321 non-null  object
 2   Subzone                                             21321 non-null  object
 3   City                                                21321 non-null  object
 4   Order ID                                            21321 non-null  int64
 5   Order Placed At                                     21321 non-null  object
 6   Order Status                                        21321 non-null  object
 7   Delivery                                            21321 non-null  object
 8   Distance                                            21321 non-null  object
 9   Items in order                                      21321 non-null  object
 10  Instructions                                        720 non-null    object
 11  Discount construct                                  15823 non-null  object
 12  Bill subtotal                                       21321 non-null  float64
 13  Packaging charges                                   21321 non-null  float64
 14  Restaurant discount (Promo)                         21321 non-null  float64
 15  Restaurant discount (Flat offs, Freebies & others)  21321 non-null  float64
 16  Gold discount                                       21321 non-null  float64
 17  Brand pack discount                                 21321 non-null  float64
 18  Total                                               21321 non-null  float64
 19  Rating                                              2491 non-null   float64
 20  Review                                              296 non-null    object
 21  Cancellation / Rejection reason                     186 non-null    object
 22  Restaurant compensation (Cancellation)              133 non-null    float64
 23  Restaurant penalty (Rejection)                      3 non-null      float64
 24  KPT duration (minutes)                              21026 non-null  float64
 25  Rider wait time (minutes)                           21153 non-null  float64
 26  Order Ready Marked                                  21321 non-null  object
 27  Customer complaint tag                              469 non-null    object
 28  Customer ID                                         21321 non-null  object
dtypes: float64(12), int64(2), object(15)
memory usage: 4.7+ MB

head-It will give we can show your first five index in your dataset

In [17]:
df.head()

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

tail-It will give we can show last five index in your dataset

In [19]:
df.tail()

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,"03:26 AM, January 30 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),...,NaN,NaN,NaN,NaN,NaN,14.32,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,"02:44 AM, January 29 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,...,NaN,NaN,NaN,NaN,NaN,NaN,10.8,Missed,NaN,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,"10:05 PM, January 24 2025",Delivered,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,...,5.0,Yummy food! Delicious food! Lip smacking food!...,NaN,NaN,NaN,16.27,9.4,Incorrectly,NaN,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,"02:27 PM, January 21 2025",Delivered,Zomato Delivery,9km,1 x Ooh Saucy Fries,...,4.0,The peri peri fries were truly so tasty and de...,NaN,NaN,NaN,12.77,1.3,Correctly,NaN,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,"02:55 AM, January 21 2025",Delivered,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,...,NaN,NaN,NaN,NaN,NaN,16.52,8.7,Correctly,NaN,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

loc-It is usefull when index of the dataframe is a lable. e.x :  Like a string

In [23]:
df.loc[12]

Restaurant ID                                                                                  20320607
Restaurant name                                                                                   Swaad
Subzone                                                                                        Sector 4
City                                                                                          Delhi NCR
Order ID                                                                                     6163201423
Order Placed At                                                             07:48 PM, September 08 2024
Order Status                                                                                  Delivered
Delivery                                                                                Zomato Delivery
Distance                                                                                            3km
Items in order                                                    1 x Bone in Smoky Bbq Grilled Chicken
Instructions                                                                                        NaN
Discount construct                                                                  50% off upto Rs.100
Bill subtotal                                                                                     310.0
Packaging charges                                                                                  10.5
Restaurant discount (Promo)                                                                       100.0
Restaurant discount (Flat offs, Freebies & others)                                                  0.0
Gold discount                                                                                       0.0
Brand pack discount                                                                                 0.0
Total                                                                                             220.5
Rating                                                                                              2.0
Review                                                                                              NaN
Cancellation / Rejection reason                                                                     NaN
Restaurant compensation (Cancellation)                                                              NaN
Restaurant penalty (Rejection)                                                                      NaN
KPT duration (minutes)                                                                            17.23
Rider wait time (minutes)                                                                           8.8
Order Ready Marked                                                                            Correctly
Customer complaint tag                                                                              NaN
Customer ID                                           db8331544bffcb3d70e0a6eacf709657d5bc03f4eec32d...
Name: 12, dtype: object

iloc-It workby looking for possition of the index

In [27]:
df.iloc[4]

Restaurant ID                                                                                  20320607
Restaurant name                                                                                   Swaad
Subzone                                                                                        Sector 4
City                                                                                          Delhi NCR
Order ID                                                                                     6167540897
Order Placed At                                                             03:04 PM, September 10 2024
Order Status                                                                                  Delivered
Delivery                                                                                Zomato Delivery
Distance                                                                                            2km
Items in order                                        1 x Peri Peri Krispers, 1 x Fried Chicken Anga...
Instructions                                                                                        NaN
Discount construct                                                                   40% off upto Rs.80
Bill subtotal                                                                                     584.0
Packaging charges                                                                                  25.2
Restaurant discount (Promo)                                                                        80.0
Restaurant discount (Flat offs, Freebies & others)                                                  0.0
Gold discount                                                                                       0.0
Brand pack discount                                                                                 0.0
Total                                                                                             529.2
Rating                                                                                              NaN
Review                                                                                              NaN
Cancellation / Rejection reason                                                                     NaN
Restaurant compensation (Cancellation)                                                              NaN
Restaurant penalty (Rejection)                                                                      NaN
KPT duration (minutes)                                                                            15.97
Rider wait time (minutes)                                                                           1.0
Order Ready Marked                                                                            Correctly
Customer complaint tag                                                                              NaN
Customer ID                                           d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
Name: 4, dtype: object

describe-We can use aggregate function in you dataset.Like a sum,mean,min,max

In [37]:
df['Rating'].describe()

count    2491.000000
mean        4.356885
std         1.181472
min         1.000000
25%         4.000000
50%         5.000000
75%         5.000000
max         5.000000
Name: Rating, dtype: float64

unique-it allow us  to display unique values from your specific column in your dataset

In [39]:
df['Restaurant name'].unique()

array(['Swaad', 'Aura Pizzas', 'Dilli Burger Adda', 'Tandoori Junction',
       'The Chicken Junction', 'Masala Junction'], dtype=object)

nunique-It will give us sum of unique values from  your specific columns in  your dataset

In [41]:
df['Restaurant name'].nunique()

6

what are the most top 5 common Restaurant ?
   * we have to use value_counts() parameter

   * It is used to count the frequency of unique value in a single column.

In [43]:
df['Restaurant name'].value_counts().head(6)

Restaurant name
Aura Pizzas             14548
Swaad                    6332
Dilli Burger Adda         227
Tandoori Junction         154
The Chicken Junction       32
Masala Junction            28
Name: count, dtype: int64

* we can use condition using in your dataset
* select from dataframe using criteria from multiple columns

In [46]:
df['Rating'].max()

5.0

In [48]:
rating=df[(df['Rating']==5) & (df['Total']>1000)]
rating

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
255,20554001,Swaad,Greater Kailash 2 (GK2),Delhi NCR,6151212614,"01:26 PM, September 04 2024",Delivered,Zomato Delivery,5km,"1 x Bone in Jamaican Grilled Chicken, 1 x Bone...",...,5.0,NaN,NaN,NaN,NaN,NaN,9.5,Missed,NaN,feaeeaa1d9d90bdbdd0ac0261a39cb5ec0fc60e5233924...
349,20635699,Aura Pizzas,Greater Kailash 2 (GK2),Delhi NCR,6164932139,"07:51 PM, September 08 2024",Delivered,Zomato Delivery,8km,"1 x Murgh Amritsari Garlic Bread, 1 x Peri Per...",...,5.0,NaN,NaN,NaN,NaN,12.05,2.4,Correctly,NaN,8d4e75110ac9e8e942aff3026100b9c7f210d6bf6228c6...
725,20659868,Aura Pizzas,Sector 4,Delhi NCR,6151715537,"05:57 PM, September 06 2024",Delivered,Zomato Delivery,8km,"2 x Makhani Paneer Pizza, 2 x Bageecha Pizza",...,5.0,NaN,NaN,NaN,NaN,11.92,2.1,Correctly,NaN,16038666aab43a92bdbd41cae17f28fa6b5babadd47527...
763,20659868,Aura Pizzas,Sector 4,Delhi NCR,6145515643,"11:12 AM, September 04 2024",Delivered,Zomato Delivery,3km,"1 x Angara Paneer Melt, 1 x Tripple Cheese Pizza",...,5.0,NaN,NaN,NaN,NaN,16.77,6.7,Correctly,NaN,a7ffcb9e4f91fbff5baeddce59654687d99e418568dacc...
861,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6160396218,"12:43 AM, September 08 2024",Delivered,Zomato Delivery,5km,"1 x Jamaican Chicken Melt, 1 x Murgh Amritsari...",...,5.0,NaN,NaN,NaN,NaN,19.52,0.8,Correctly,NaN,94208e62fe6e67c8ade26a0de895ecd7c321613566b62d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20913,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6555732277,"07:20 PM, January 25 2025",Delivered,Zomato Delivery,13km,"1 x Tripple Cheese Pizza, 1 x Masala Paneer Pi...",...,5.0,NaN,NaN,NaN,NaN,20.80,12.1,Correctly,NaN,09b884a021294bb93d65b6b9b0000e988397bac3dccfd3...
20932,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6548407789,"11:39 AM, January 25 2025",Delivered,Zomato Delivery,6km,"1 x Combo For 1 - Non Veg, 1 x Combo For 1 - N...",...,5.0,NaN,NaN,NaN,NaN,33.15,16.8,Correctly,NaN,8e0cc9e8202a08b004821e019f86820db8e15761635fd1...
20966,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6545468310,"08:48 PM, January 22 2025",Delivered,Zomato Delivery,2km,"1 x Peri Peri Paneer Pizza, 1 x Makhani Paneer...",...,5.0,NaN,NaN,NaN,NaN,20.12,4.1,Correctly,NaN,bc632ac8d41efa8256c98b431bfdcb268431c798d8dbb9...
21160,21077127,Aura Pizzas,Sector 135,Delhi NCR,6558366401,"07:02 PM, January 28 2025",Delivered,Zomato Delivery,4km,"1 x Just Pepperoni Pizza, 1 x Bellpepper Onion...",...,5.0,NaN,NaN,NaN,NaN,17.88,12.3,Correctly,NaN,4432ad8a54cb1850e5c157c79c06f64f229dcbbb931e5d...
21232,21077127,Aura Pizzas,Sector 135,Delhi NCR,6538525312,"08:15 PM, January 21 2025",Delivered,Zomato Delivery,17km,"1 x Loaded Pork Pepperoni Pizza, 1 x Indian Ma...",...,5.0,NaN,NaN,NaN,NaN,15.67,5.2,Correctly,NaN,3ad6f6c76f7db4a08b9cc96ae915dd0795ff1f7c52e7a0...

isnull-we can show your nan value columns in your dataset

In [50]:
df[df.isnull().any(axis=1)]

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,"03:26 AM, January 30 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),...,NaN,NaN,NaN,NaN,NaN,14.32,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,"02:44 AM, January 29 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,...,NaN,NaN,NaN,NaN,NaN,NaN,10.8,Missed,NaN,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,"10:05 PM, January 24 2025",Delivered,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,...,5.0,Yummy food! Delicious food! Lip smacking food!...,NaN,NaN,NaN,16.27,9.4,Incorrectly,NaN,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,"02:27 PM, January 21 2025",Delivered,Zomato Delivery,9km,1 x Ooh Saucy Fries,...,4.0,The peri peri fries were truly so tasty and de...,NaN,NaN,NaN,12.77,1.3,Correctly,NaN,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,"02:55 AM, January 21 2025",Delivered,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,...,NaN,NaN,NaN,NaN,NaN,16.52,8.7,Correctly,NaN,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

In [52]:
df.isnull().sum()

Restaurant ID                                             0
Restaurant name                                           0
Subzone                                                   0
City                                                      0
Order ID                                                  0
Order Placed At                                           0
Order Status                                              0
Delivery                                                  0
Distance                                                  0
Items in order                                            0
Instructions                                          20601
Discount construct                                     5498
Bill subtotal                                             0
Packaging charges                                         0
Restaurant discount (Promo)                               0
Restaurant discount (Flat offs, Freebies & others)        0
Gold discount                                             0
Brand pack discount                                       0
Total                                                     0
Rating                                                18830
Review                                                21025
Cancellation / Rejection reason                       21135
Restaurant compensation (Cancellation)                21188
Restaurant penalty (Rejection)                        21318
KPT duration (minutes)                                  295
Rider wait time (minutes)                               168
Order Ready Marked                                        0
Customer complaint tag                                20852
Customer ID                                               0
dtype: int64

dropna-It allow us to delete all nan value (columns/rows) in your dataset

In [ ]:
df_new=df.dropna(axis=1)
df_new

fillna-it allow us fill nan values using any aggregate function

In [61]:
fill_na=df.fillna(df['Total'].mean())
fill_na

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,682.616113,682.616113,682.616113,682.616113,682.616113,18.350000,11.6,Correctly,682.616113,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,682.616113,682.616113,682.616113,682.616113,682.616113,16.950000,3.6,Correctly,682.616113,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,682.616113,682.616113,682.616113,682.616113,682.616113,14.050000,12.2,Correctly,682.616113,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.000000,682.616113,682.616113,682.616113,682.616113,19.000000,3.3,Correctly,682.616113,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,682.616113,682.616113,682.616113,682.616113,682.616113,15.970000,1.0,Correctly,682.616113,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,"03:26 AM, January 30 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),...,682.616113,682.616113,682.616113,682.616113,682.616113,14.320000,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,"02:44 AM, January 29 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,...,682.616113,682.616113,682.616113,682.616113,682.616113,682.616113,10.8,Missed,682.616113,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,"10:05 PM, January 24 2025",Delivered,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,...,5.000000,Yummy food! Delicious food! Lip smacking food!...,682.616113,682.616113,682.616113,16.270000,9.4,Incorrectly,682.616113,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,"02:27 PM, January 21 2025",Delivered,Zomato Delivery,9km,1 x Ooh Saucy Fries,...,4.000000,The peri peri fries were truly so tasty and de...,682.616113,682.616113,682.616113,12.770000,1.3,Correctly,682.616113,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,"02:55 AM, January 21 2025",Delivered,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,...,682.616113,682.616113,682.616113,682.616113,682.616113,16.520000,8.7,Correctly,682.616113,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

In [59]:
df.isnull().mean()

Restaurant ID                                         0.000000
Restaurant name                                       0.000000
Subzone                                               0.000000
City                                                  0.000000
Order ID                                              0.000000
Order Placed At                                       0.000000
Order Status                                          0.000000
Delivery                                              0.000000
Distance                                              0.000000
Items in order                                        0.000000
Instructions                                          0.966230
Discount construct                                    0.257868
Bill subtotal                                         0.000000
Packaging charges                                     0.000000
Restaurant discount (Promo)                           0.000000
Restaurant discount (Flat offs, Freebies & others)    0.000000
Gold discount                                         0.000000
Brand pack discount                                   0.000000
Total                                                 0.000000
Rating                                                0.883167
Review                                                0.986117
Cancellation / Rejection reason                       0.991276
Restaurant compensation (Cancellation)                0.993762
Restaurant penalty (Rejection)                        0.999859
KPT duration (minutes)                                0.013836
Rider wait time (minutes)                             0.007880
Order Ready Marked                                    0.000000
Customer complaint tag                                0.978003
Customer ID                                           0.000000
dtype: float64

groupby-you can use groupby meathod to group rows together based off of a column name

In [63]:
dis=df.groupby('Distance')['Total'].mean()
a=dis.sort_values()[::-1]
a

Distance
21km    1167.075000
18km    1156.629600
19km    1003.921579
15km     957.559351
12km     920.037565
13km     913.849365
16km     913.221724
14km     881.337561
10km     866.701510
11km     817.697945
9km      803.451565
17km     802.719231
20km     743.750000
8km      729.916714
7km      726.420757
6km      686.502917
4km      681.286473
<1km     672.476040
3km      655.700953
5km      653.948192
2km      645.267451
1km      644.778410
Name: Total, dtype: float64

In [67]:
dis.sum()

18044.249900586106

Grouping rows by time

In [72]:
df['Order Placed At']=pd.to_datetime(df['Order Placed At'])
df['Order Placed At']

0       2024-09-10 23:38:00
1       2024-09-10 23:34:00
2       2024-09-10 15:52:00
3       2024-09-10 15:45:00
4       2024-09-10 15:04:00
                ...
21316   2025-01-30 03:26:00
21317   2025-01-29 02:44:00
21318   2025-01-24 22:05:00
21319   2025-01-21 14:27:00
21320   2025-01-21 02:55:00
Name: Order Placed At, Length: 21321, dtype: datetime64[ns]

**Applying function to create 2 columns called year,month**

In [74]:
df['year']=df['Order Placed At'].apply(lambda x:x.year)
df['year']

0        2024
1        2024
2        2024
3        2024
4        2024
         ...
21316    2025
21317    2025
21318    2025
21319    2025
21320    2025
Name: year, Length: 21321, dtype: int64

In [76]:
df.groupby(df['year'])['Rating'].mean()

year
2024    4.340737
2025    4.419608
Name: Rating, dtype: float64

In [78]:
df['month']=df['Order Placed At'].apply(lambda x:x.month)
df['month'].sort_values()

21320     1
18652     1
18651     1
18650     1
18649     1
         ..
15796    12
15797    12
15798    12
15792    12
17045    12
Name: month, Length: 21321, dtype: int64

**Create Month wise Total Sales**

In [80]:
df['month'].unique()

array([ 9, 10, 11, 12,  1], dtype=int64)

In [62]:
df.groupby(df['month'])['Total'].mean()

month
1     701.301162
9     618.143971
10    704.447096
11    671.685919
12    718.467545
Name: Total, dtype: float64

**Create City wise Total sales**

In [84]:
df['City'].unique()

array(['Delhi NCR'], dtype=object)

**Create subzone wise Total sales**

In [66]:
df.groupby('Subzone')['Total'].mean()

Subzone
Chittaranjan Park          474.810000
DLF Phase 1                706.573413
Greater Kailash 2 (GK2)    644.477978
Sector 135                 720.349554
Sector 4                   688.222763
Shahdara                   691.962222
Sikandarpur                441.000000
Vasant Kunj                749.669337
Name: Total, dtype: float64

**Create Restaurant Wise Total Sales**

In [88]:
df.groupby('Restaurant name')['Total'].sum()

Restaurant name
Aura Pizzas             10751617.42
Dilli Burger Adda         101709.62
Masala Junction             9162.30
Swaad                    3545521.86
Tandoori Junction         133665.95
The Chicken Junction       12380.99
Name: Total, dtype: float64

In [90]:
df.head()

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID,year,month
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,2024-09-10 23:38:00,Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...,2024,9
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,2024-09-10 23:34:00,Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...,2024,9
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,2024-09-10 15:52:00,Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...,2024,9
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,2024-09-10 15:45:00,Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...,2024,9
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,2024-09-10 15:04:00,Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...,2024,9

**Top 5 Ordered Iteams in the Restaurant**

In [94]:
df['Items in order']=df['Items in order'].apply(lambda x:x.split(',')[0])
df['Items in order'].value_counts().head()

Items in order
1 x Bageecha Pizza                      1785
1 x Bone in Jamaican Grilled Chicken     982
1 x All About Chicken Pizza              892
1 x Chilli Cheese Garlic Bread           853
1 x Makhani Paneer Pizza                 816
Name: count, dtype: int64